# This is the mods.toml file using placeholders for build script expansion.

modLoader="javafml" #mandatory
# Use the placeholder defined in gradle.properties
loaderVersion="${loader_version_range}" #mandatory
# Use the placeholder defined in gradle.properties
license="${mod_license}"
# You can keep this hardcoded or make it a property if you prefer
issueTrackerURL="https://github.com/alafortu/SuperMom_mcraft_mod/issues" #optional

[[mods]] #mandatory
# Use the placeholder defined in gradle.properties
modId="${mod_id}" #mandatory
# Use the placeholder defined in gradle.properties - THIS replaces file.jarVersion here
version="${mod_version}" #mandatory
# Use the placeholder defined in gradle.properties
displayName="${mod_name}" #mandatory
# You can keep this hardcoded or make it a property if you prefer
displayURL="https://github.com/alafortu/SuperMom_mcraft_mod" #optional
# Use the placeholder defined in gradle.properties
authors="${mod_authors}" #optional
# Use the placeholder defined in gradle.properties
description='''${mod_description}''' #mandatory

# Specify required dependencies using placeholders
# IMPORTANT: The dependency block name itself must use the placeholder!
[[dependencies.${mod_id}]] #Optional but standard
    modId="forge" #mandatory
    mandatory=true #mandatory
    # Use the placeholder defined in gradle.properties
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]] #Optional but standard
    modId="minecraft" #mandatory
    mandatory=true #mandatory
    # Use the placeholder defined in gradle.properties
    versionRange="${minecraft_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"